require("configs.settings")
require("configs.mappings")
require("plugins.packages")
require("plugins.plugins")
require("plugins.staline")
require("plugins.indent")
require("plugins.treesitter")
require("plugins.catppuccin")
require("plugins.autopairs")
require("plugins.autocomplete")
require("plugins.nvimtree")

